apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: karydia
  labels:
    app: karydia
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: karydia
    spec:
      containers:
      - name: karydia
        image: kinvolk/karydia
        imagePullPolicy: IfNotPresent
        command:
          - karydia
          - runserver
          - --tls-cert
          - /etc/karydia/tls/cert.pem
          - --tls-key
          - /etc/karydia/tls/key.pem
          - --enable-default-network-policy
          - --enable-karydia-admission
        volumeMounts:
          - name: karydia-tls
            mountPath: /etc/karydia/tls
        livenessProbe:
          httpGet:
            path: /healthz
            port: 33333
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          failureThreshold: 2
        ports:
        - containerPort: 33333
      - name: opa
        image: openpolicyagent/opa:0.10.1
        imagePullPolicy: IfNotPresent
        args:
          - "run"
          - "--server"
          - "--addr=http://127.0.0.1:8181"
      - name: kube-mgmt
        image: openpolicyagent/kube-mgmt:0.7
        imagePullPolicy: Always
        args:
          - "--replicate-cluster=v1/pods"
      volumes:
        - name: karydia-tls
          secret:
            secretName: karydia-tls
