sudo: required

language: go

# Versions of go that are explicitly supported by gonum.
go:
 - 1.12.x
 - 1.11.x
 - 1.10.x
 - master

go_import_path: gonum.org/v1/netlib

os:
 - linux
 - osx

env:
 global:
  - GO111MODULE=on
 matrix:
  - BLAS_LIB=OpenBLAS
  # Does not currently link correctly.  Note that there is an issue with drotgm in ATLAS.
  # - BLAS_LIB=ATLAS
  # If we can get multiarch builds on travis.
  # There are some issues with the Accellerate implementation.
  #- BLAS_LIB=Accellerate

cache:
 directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod

git:
 depth: 1

matrix:
 fast_finish: true
 allow_failures:
   - go: master
 exclude:
  - os: linux
    env: BLAS_LIB=Accelerate
  - os: linux
    env: BLAS_LIB=ATLAS
  - os: osx
    env: BLAS_LIB=ATLAS
  - os: osx
    env: BLAS_LIB=OpenBLAS

before_install:
 # Required for format check.
 - go get golang.org/x/tools/cmd/goimports
 # Required for code get checks.
 - go mod download gonum.org/v1/gonum || true
 # Required for imports check.
 - go get gonum.org/v1/tools/cmd/check-imports
 # Required for copyright header check.
 - go get gonum.org/v1/tools/cmd/check-copyright

# Cache used to persist the compiled BLAS library between CI calls.
cache:
  directories:
  - .travis/OpenBLAS.cache

# Install the appropriate blas library (if any) and associated gonum software.
install:
 - travis_wait 20 ${TRAVIS_BUILD_DIR}/.travis/$TRAVIS_OS_NAME/$BLAS_LIB/install.sh

script:
 - ${TRAVIS_BUILD_DIR}/.travis/check-copyright.sh
 - ${TRAVIS_BUILD_DIR}/.travis/check-imports.sh
 - ${TRAVIS_BUILD_DIR}/.travis/check-formatting.sh
 - ${TRAVIS_BUILD_DIR}/.travis/$TRAVIS_OS_NAME/$BLAS_LIB/test.sh
 # This is run last since it alters the tree.
 - ${TRAVIS_BUILD_DIR}/.travis/check-generate.sh
